function getKeyNoteMaps(){
    return {
        "TypersSplit" : {
            "description": "This layout starts at 'z' and goes higher through 'h', then jumps to 'a' thru 'g', then jump to 'q' thru 't', then 'n' thru '.', then 'h' thru ';', then 'y' thru 'p'.  It reminds me the home key style of typing.",
            "keyNoteMap":{
                "z": "D2",
                "x": "E2",
                "c": "F2",
                "v": "G2",
                "b": "A2",
                "a": "B2",
                "s": "C3",
                "d": "D3",
                "f": "E3",
                "g": "F3",
                "q": "G3",
                "w": "A3",
                "e": "B3",
                "r": "C4",
                "t": "D4",
                "n": "E4",
                "m": "F4",
                ",": "G4",
                ".": "A4",
                "h": "B4",
                "j": "C5",
                "k": "D5",
                "l": "E5",
                ";": "F5",
                "y": "G5",
                "u": "A5",
                "i": "B5",
                "o": "C6",
                "p": "D6"
            }
            
        },
        "HorizontalZToP":{
            "description":"This layout starts at 'z' and goes higher thru '.', then it jumps to 'a' thru ';', then jumps to 'q' thru 'p'.  It reminds me the most of a natural instrumental pattern.",
            "keyNoteMap": {
                "z": "D2",
                "x": "E2",
                "c": "F2",
                "v": "G2",
                "b": "A2",
                "n": "B2",
                "m": "C3",
                ",": "D3",
                ".": "E3",
                "a": "F3",
                "s": "G3",
                "d": "A3",
                "f": "B3",
                "g": "C4",
                "h": "D4",
                "j": "E4",
                "k": "F4",
                "l": "G4",
                ";": "A4",
                "q": "B4",
                "w": "C5",
                "e": "D5",
                "r": "E5",
                "t": "F5",
                "y": "G5",
                "u": "A5",
                "i": "B5",
                "o": "C6",
                "p": "D6"
            }            
        },
        "VerticalZToP":{
            "description":"This layout starts at 'z' and goes higher upward thrue 'q', then jumps to 'x' thru 'w', then 'c' thru 'e', and so on that way.  I am not sure what type of instrument it reminds me of, but maybe it makes sense to someone!",
            "keyNoteMap": {
                "z": "D2",
                "a": "E2",
                "q": "F2",
                "x": "G2",
                "s": "A2",
                "w": "B2",
                "c": "C3",
                "d": "D3",
                "e": "E3",
                "v": "F3",
                "f": "G3",
                "r": "A3",
                "b": "B3",
                "g": "C4",
                "t": "D4",
                "n": "E4",
                "h": "F4",
                "y": "G4",
                "m": "A4",
                "j": "B4",
                "u": "C5",
                ",": "D5",
                "k": "E5",
                "i": "F5",
                ".": "G5",
                "l": "A5",
                "o": "B5",
                ";": "C6",
                "p": "D6"
            }
        }
    };
}