/**
 * CR 001 Phase 6 — tempo suggestion E2E (E2E-4.1…E2E-4.4), Playwright, chromium.
 *
 * Fixture: test/fixtures/clicks20.wav — a 120 BPM click train (40 clicks at
 * 0.5 s spacing, 1568/1047 Hz bursts; generated by
 * scripts/make-clicks20-wav.cjs, D-K). Negative fixture: sine3s.mp3
 * (3 s → too few onsets → detectTempo null, TD-1.11).
 *
 * Conventions:
 *   - R-9: NEVER assert the fixture's duration string — BPM field, hint,
 *     and announcement only
 *   - the prefill is a post-Ready async task (setTimeout(0) yield + <50 ms
 *     detection budget, PERF-1). Positive rows poll for the hint/
 *     announcement (state existence, no timing claim). Negative rows
 *     cannot poll for absence (it holds from t=0) — they instead watch the
 *     whole detection window in-page (MutationObserver + 5 ms sweep) so
 *     "no hint / no announcement" means "never appeared while detection
 *     was resolving", not "not yet"
 *   - never listen to audio
 */

const { test, expect } = require('@playwright/test');
const path = require('path');
const {
  waitForAppMount, expectReady, FIXTURE
} = require('./helpers.cjs');

const CLICKS20 = path.join(__dirname, '..', 'fixtures', 'clicks20.wav');

/**
 * Re-pin note (2026-08-25, platform invariants — the plan's E2E-4.4 "Then"
 * "the field still shows the user's draft" is not reachable in a browser
 * via ANY load trigger):
 *   1. a drop event — trusted OR synthetic — moves focus (native drop
 *      focus semantics; verified in-page with a focusin/focusout trace);
 *   2. even a load that does not move focus blurs the field, because
 *      decoding flips isReady → `:disabled="!isReady"` on #bpmInput, and a
 *      focused element that becomes disabled loses focus;
 *   3. the app's commit-on-blur law (RD-1, @blur="commitBpmEntry") then
 *      commits the very draft W-16 protects — the draft is never "live"
 *      at detection time.
 * The no-clobber guarantee for a genuinely live mid-draft therefore lives
 * at the P0 unit level (TD-U1.4/TD-U1.5: gate clause 3 focus + clause 4
 * draft, read at write time, R-10). This row pins the reachable
 * literal-step behavior instead: focused divergent draft + drop → the
 * draft is committed by the app's OWN blur law (9 → clamped 30), the
 * re-drop's flag reset (CR §2.5 row 1) lets the suggestion land, and it
 * lands VISIBLY — field "120" + hint + announcement, with the stale clamp
 * hint cleared by the prefill (D-H hint mutual exclusion). The user's
 * committed value is never replaced silently.
 */

/** The pinned hint string for the 120 BPM fixture (W-3, short form). */
const HINT_120 = 'Detected ~120 BPM';
const ANN_120 = 'Detected tempo 120 BPM';

/** The live region (V-07 polite announcements) — the div, not the hint <p>. */
const liveRegion = (page) => page.locator('div.sr-only[role="status"]');

/** The tempo hint paragraph inside the BPM control group. */
const tempoHint = (page) => page.locator('.controls p.clamp-hint').filter({ hasText: /Detected ~/ });

/**
 * Watch the app for a bounded window (in-page) and report whether the tempo
 * hint or the "Detected tempo" announcement EVER appeared. In-page because
 * the node-side poll is starved under load and a node "absence" check can
 * race the detection task. The window (500 ms) dwarfs the detection budget
 * (<50 ms, PERF-1); the initial check() covers a detection that already
 * finished before the watcher installed.
 */
async function watchForTempoSignals(page, ms = 500) {
  return page.evaluate((windowMs) => new Promise((resolve) => {
    let sawHint = false;
    let sawAnnouncement = false;
    const check = () => {
      for (const p of document.querySelectorAll('.controls p.clamp-hint')) {
        if (/^Detected ~\d+ BPM$/.test(p.textContent)) sawHint = true;
      }
      const live = document.querySelector('div.sr-only[role="status"]');
      if (live && /Detected tempo \d+ BPM/.test(live.textContent)) sawAnnouncement = true;
    };
    check();
    const mo = new MutationObserver(check);
    mo.observe(document.getElementById('app'), { subtree: true, childList: true, characterData: true });
    const iv = setInterval(check, 5);
    setTimeout(() => {
      mo.disconnect();
      clearInterval(iv);
      resolve({ sawHint, sawAnnouncement });
    }, windowMs);
  }), ms);
}

/** The peaks and tempo tasks share the post-load yield batch (D-E); the
 *  painted canvas is the node-side-visible marker that the batch ran. */
async function expectPostLoadBatchRan(page) {
  await expect(page.locator('#waveformCanvas')).toHaveAttribute('data-loaded', 'true', { timeout: 10000 });
}

test.describe('CR 001 Phase 6 — tempo suggestion (E2E-4.x)', () => {
  test('E2E-4.1 prefill happy path: field + hint + announcement', async ({ page }) => {
    await waitForAppMount(page);
    await page.setInputFiles('#fileInput', CLICKS20);
    await expectReady(page);

    // The hint is the positive proof the prefill WROTE — the field default
    // is already "120", so the value alone proves nothing.
    await expect(tempoHint(page)).toBeVisible({ timeout: 10000 });
    await expect(tempoHint(page)).toHaveText(HINT_120);
    await expect(page.locator('#bpmInput')).toHaveValue('120');
    await expect(liveRegion(page)).toHaveText(ANN_120);
    // The suggestion hint and the bpmClamped hint never coexist: 120 is in
    // range, so exactly one hint (the suggestion) is in the BPM group.
    expect(await page.locator('.controls p.clamp-hint').count()).toEqual(1);
  });

  test('E2E-4.2 flag reset on load — re-drop re-suggests (CR §2.5 row 1)', async ({ page }) => {
    await waitForAppMount(page);
    await page.setInputFiles('#fileInput', CLICKS20);
    await expectReady(page);
    await expect(tempoHint(page)).toBeVisible({ timeout: 10000 });

    // User touch: edit + commit (the touched flag is set).
    await page.fill('#bpmInput', '140');
    await page.keyboard.press('Enter');
    await expect(page.locator('#bpmInput')).toHaveValue('140');

    // Re-drop the SAME file: the successful load resets the flag → the
    // prefill happens AGAIN (the design memo's "no prefill on re-drop" was
    // wrong — the CR is authoritative).
    await page.setInputFiles('#fileInput', CLICKS20);
    await expectReady(page);
    // The field returns from 140 — the real, observable re-prefill.
    await expect(page.locator('#bpmInput')).toHaveValue('120', { timeout: 10000 });
    await expect(tempoHint(page)).toBeVisible();
    await expect(liveRegion(page)).toHaveText(ANN_120);
  });

  test('E2E-4.3 negative fixture stays silent (null → no prefill, no hint, no announcement)', async ({ page }) => {
    await waitForAppMount(page);
    const valueBefore = await page.locator('#bpmInput').inputValue();
    await page.setInputFiles('#fileInput', FIXTURE);
    await expectReady(page);
    await expectPostLoadBatchRan(page);

    // 3 s → too few onsets → detectTempo null (TD-1.11): the whole
    // detection window must stay silent, not just the final state.
    const signals = await watchForTempoSignals(page);
    expect(signals.sawHint, 'no "Detected ~N BPM" hint').toEqual(false);
    expect(signals.sawAnnouncement, 'no "Detected tempo N BPM" announcement').toEqual(false);
    await expect(page.locator('#bpmInput')).toHaveValue(valueBefore); // unchanged
    await expect(liveRegion(page)).toHaveText('sine3s.mp3 loaded'); // still the LOAD announcement
  });

  test('E2E-4.4 focused mid-draft + drop: the blur law commits first; the suggestion then lands visibly (W-16 re-pin — see header note)', async ({ page }) => {
    await waitForAppMount(page);
    // Land a first suggestion so the gate is known-passable pre-touch…
    await page.setInputFiles('#fileInput', CLICKS20);
    await expectReady(page);
    await expect(tempoHint(page)).toBeVisible({ timeout: 10000 });
    // …then leave a focused, divergent draft ("9" ≠ model 120). fill()
    // focuses the field and its input event sets the touched flag
    // (CR §2.5 row 4); the draft write is v-model's.
    await page.fill('#bpmInput', '9');
    await expect(page.locator('#bpmInput')).toHaveValue('9');

    // Re-drop: decoding disables the field → blur → the app's own commit
    // law commits "9" (clamped to 30); the successful load resets the flag
    // (CR §2.5 row 1) and the detection re-suggests — VISIBLY.
    await page.setInputFiles('#fileInput', CLICKS20);
    await expect(page.locator('#bpmInput')).toHaveValue('120', { timeout: 10000 });
    await expect(tempoHint(page)).toBeVisible();
    await expect(tempoHint(page)).toHaveText(HINT_120);
    await expect(liveRegion(page)).toHaveText(ANN_120);
    // The prefill's in-range write cleared the stale clamp hint — the two
    // hints never coexist (D-H mutual exclusion).
    expect(await page.locator('.controls p.clamp-hint').count()).toEqual(1);
  });
});
