function getChallengeScores(){
    var challengeScores = {        
        "bach_inv1C_COM.MID_normal": "6000",
        "anon_jbells_com.mid_crazy": "9150",
        "vivaldi_4s_winter.mid_hard": "15750",
        "bach_branconc2F_III_com.mid_hard": "26650",
        "bach_prelude1.mid_normal": "10700",
        "bach_prelude1.mid_hard": "11550",
        "straus_blued_II_com.mid_normal": "6150",
        "vivaldi_4s_winter.mid_normal": "13400",
        "debussy_gollycake.mid_crazy": "21600",
        "anon_als_com.mid_crazy": "9650",
        "anon_als_com.mid_normal": "6200",
        "handel_firewk_mus.mid_crazy": "7600",
        "arbeau_matachins.mid_crazy": "14000",
        "mozart-piano-concerto-21-2-elvira-madigan-piano-solo.mid_normal": "40750",
        "bach_branconc2F_III_com.mid_crazy": "27900",
        "bach_theGigueFugue.mid_hard": "29950",
        "bach_2partInvention.mid_normal": "7050",
        "anon_firnoel_com.mid_normal": "5000",
        "anon_firnoel_com.mid_hard": "5000",
        "handel_sheba_pno.mid_crazy": "26600",
        "bach_prelude1.mid_crazy": "13150",
        "schubert_serenade.mid_hard": "14700",
        "vivaldi_4s_winter.mid_crazy": "16800",
        "bach_inv1C_COM.MID_crazy": "9800",
        "anon_jbells_com.mid_normal": "3900",
        "schubert_symph_5.mid_hard": "15950",
        "bach_2partInvention.mid_hard": "9300",
        "grieg_hallofking.mid_hard": "19800",
        "schubert_symph_5.mid_normal": "13750",
        "debussy_gollycake.mid_normal": "18950",
        "bach_theGigueFugue.mid_crazy": "36350",
        "debussy_gollycake.mid_hard": "21050",
        "bach_branconc2F_I_com.mid_normal": "33200",
        "tchaik_lakescene.mid_normal": "19450",
        "vivaldi_4s_spring.mid_crazy": "18200",
        "tchaik_lakescene.mid_crazy": "21950",
        "schumann_soldier_m.mid_normal": "3900",
        "handel_firewk_mus.mid_normal": "5350",
        "straus_blued_II_com.mid_crazy": "8600",
        "vivaldi_4s_spring.mid_normal": "12500",
        "straus_blued_II_com.mid_hard": "8400",
        "straus_blued_IV_com.mid_hard": "14700",
        "tchaik_trepak.mid_hard": "11050",
        "vivaldi_4s_spring.mid_hard": "14450",
        "teleman_sonata_f.mid_hard": "16600",
        "schubert_serenade.mid_crazy": "15000",
        "bach_branconc2F_III_com.mid_normal": "24150",
        "grieg_hallofking.mid_crazy": "22200",
        "tchaik_trepak.mid_normal": "8100",
        "bach_gavotte.mid_crazy": "12450",
        "straus_blued_III_com.mid_normal": "13150",
        "straus_blued_III_com.mid_crazy": "19050",
        "bach_2partInvention.mid_crazy": "10750",
        "straus_blued_IV_com.mid_crazy": "18100",
        "arbeau_matachins.mid_hard": "12500",
        "bach_inv1C_COM.MID_hard": "7600",
        "grieg_hallofking.mid_normal": "18300",
        "schubert_symph_5.mid_crazy": "19950",
        "straus_blued_III_com.mid_hard": "15550",
        "tchaik_trepak.mid_crazy": "11500",
        "teleman_sonata_f.mid_crazy": "18300",
        "straus_blued_IV_com.mid_normal": "11500",
        "handel_sheba_pno.mid_normal": "17350",
        "anon_firnoel_com.mid_crazy": "8950",
        "bach_gavotte.mid_hard": "10800",
        "mozart-piano-concerto-21-2-elvira-madigan-piano-solo.mid_hard": "53250",
        "wanton_maidens.mid_crazy": "8900",
        "mozart_elvira_m.mid_crazy": "57400",
        "schumann_soldier_m.mid_hard": "4800",
        "mozart_elvira_m.mid_hard": "49700",
        "wanton_maidens.mid_normal": "6650",
        "arbeau_matachins.mid_normal": "10800",
        "schubert_serenade.mid_normal": "11700",
        "anon_jbells_com.mid_hard": "6100",
        "handel_sheba_pno.mid_hard": "23700",
        "schumann_soldier_m.mid_crazy": "5600",
        "mozart-piano-concerto-21-2-elvira-madigan-piano-solo.mid_crazy": "66700",
        "tchaik_lakescene.mid_hard": "20750",
        "bach_gavotte.mid_normal": "8950",
        "teleman_sonata_f.mid_normal": "14000",
        "wanton_maidens.mid_hard": "8400",
        "bach_branconc2F_I_com.mid_hard": "42550",
        "anon_als_com.mid_hard": "9700",
        "bach_theGigueFugue.mid_normal": "26000",
        "handel_firewk_mus.mid_hard": "6600",
        "mozart_elvira_m.mid_normal": "36600"          
    };

    return {
        getSelectedScore: function(midiFileName, difficulty) {
            var key = midiFileName + "_" + difficulty;
            debugger;
            if(challengeScores[key]){
                return challengeScores[key];
            }
            return "";
        }
    }
}