function getKeyNoteMaps(){
    return {
        "HorizontalZTo0":{
            "description":"This layout include half steps as part of the progression, and it extends from the 'z' key, all the way to the '0' key.",
            "keyNoteMap":{
                "z": "D3",
                "x": "D#3",
                "c": "E3",
                "v": "F3",
                "b": "F#3",
                "n": "G3",
                "m": "G#3",
                ",": "A3",
                ".": "A#3",
                "a": "B3",
                "s": "C4",
                "d": "C#4",
                "f": "D4",
                "g": "D#4",
                "h": "E4",
                "j": "F4",
                "k": "F#4",
                "l": "G4",
                ";": "G#4",
                "q": "A4",
                "w": "A#4",
                "e": "B4",
                "r": "C5",
                "t": "C#5",
                "y": "D5",
                "u": "D#5",
                "i": "E5",
                "o": "F5",
                "p": "F#5",
                "1": "G5",
                "2": "G#5",
                "3": "A5",
                "4": "A#5",
                "5": "B5",
                "6": "C6",
                "7": "C#6",
                "8": "D6",
                "9": "D#6",
                "0": "E6"
            }
        },
        "VerticalZTo0":{
            "description":"This layout include half steps as part of the progression, and it extends from the 'z' key, all the way to the '0' key, going upward, like 'z', 'a', 'q', '1', 'x'....",
            "keyNoteMap":{
                "z": "D3",
                "a": "D#3",
                "q": "E3",
                "1": "F3",
                "x": "F#3",
                "s": "G3",
                "w": "G#3",
                "2": "A3",
                "c": "A#3",
                "d": "B3",
                "e": "C4",
                "3": "C#4",
                "v": "D4",
                "f": "D#4",
                "r": "E4",
                "4": "F4",
                "b": "F#4",
                "g": "G4",
                "t": "G#4",
                "5": "A4",
                "n": "A#4",
                "h": "B4",
                "y": "C5",
                "6": "C#5",
                "m": "D5",
                "j": "D#5",
                "u": "E5",
                "7": "F5",
                ",": "F#5",
                "k": "G5",
                "i": "G#5",
                "8": "A5",
                ".": "A#5",
                "l": "B5",
                "o": "C6",
                "9": "C#6",
                ";": "D6",
                "p": "D#6",
                "0": "E6"
            }
        },
        "TypersSplitZToP" : {
            "description": "This layout starts at 'z' and goes higher through 'h', then jumps to 'a' thru 'g', then jump to 'q' thru 't', then 'n' thru '.', then 'h' thru ';', then 'y' thru 'p'.  It reminds me the home key style of typing.",
            "keyNoteMap":{
                "z": "D2",
                "x": "E2",
                "c": "F2",
                "v": "G2",
                "b": "A2",
                "a": "B2",
                "s": "C3",
                "d": "D3",
                "f": "E3",
                "g": "F3",
                "q": "G3",
                "w": "A3",
                "e": "B3",
                "r": "C4",
                "t": "D4",
                "n": "E4",
                "m": "F4",
                ",": "G4",
                ".": "A4",
                "h": "B4",
                "j": "C5",
                "k": "D5",
                "l": "E5",
                ";": "F5",
                "y": "G5",
                "u": "A5",
                "i": "B5",
                "o": "C6",
                "p": "D6"
            }

        },
        "HorizontalZToP":{
            "description":"This layout starts at 'z' and goes higher thru '.', then it jumps to 'a' thru ';', then jumps to 'q' thru 'p'.  It reminds me the most of a natural instrumental pattern.",
            "keyNoteMap": {
                "z": "D2",
                "x": "E2",
                "c": "F2",
                "v": "G2",
                "b": "A2",
                "n": "B2",
                "m": "C3",
                ",": "D3",
                ".": "E3",
                "a": "F3",
                "s": "G3",
                "d": "A3",
                "f": "B3",
                "g": "C4",
                "h": "D4",
                "j": "E4",
                "k": "F4",
                "l": "G4",
                ";": "A4",
                "q": "B4",
                "w": "C5",
                "e": "D5",
                "r": "E5",
                "t": "F5",
                "y": "G5",
                "u": "A5",
                "i": "B5",
                "o": "C6",
                "p": "D6"
            }
        },
        "VerticalZToP":{
            "description":"This layout starts at 'z' and goes higher upward thru 'q', then jumps to 'x' thru 'w', then 'c' thru 'e', and so on that way.  I am not sure what type of instrument it reminds me of, but maybe it makes sense to someone!",
            "keyNoteMap": {
                "z": "D2",
                "a": "E2",
                "q": "F2",
                "x": "G2",
                "s": "A2",
                "w": "B2",
                "c": "C3",
                "d": "D3",
                "e": "E3",
                "v": "F3",
                "f": "G3",
                "r": "A3",
                "b": "B3",
                "g": "C4",
                "t": "D4",
                "n": "E4",
                "h": "F4",
                "y": "G4",
                "m": "A4",
                "j": "B4",
                "u": "C5",
                ",": "D5",
                "k": "E5",
                "i": "F5",
                ".": "G5",
                "l": "A5",
                "o": "B5",
                ";": "C6",
                "p": "D6"
            }
        }
    };
}